dist: bionic
language: csharp
mono: none
dotnet: 3.1.300
script:
 - dotnet publish -r linux-arm -c Release

before_deploy:
  - pip install cloudsmith-cli
  - export PACKAGE_FILE_NAME=HelloFsharp-${TRAVIS_TAG}.tar.gz
  - tar -zcf ${PACKAGE_FILE_NAME} bin\Release\netcoreapp3.1\linux-arm\publish\

deploy:
  provider: script
  skip_cleanup: true
  script: cloudsmith push raw bartosz-podlejski/hellofsharp ${PACKAGE_FILE_NAME}
  on:
    branch: master
